### ISSUE TITLE
can image convert to DDS?

### ISSUE THREAD

**Issue by junglelan** [Dahie/DDS-Utils#16]

**Comment by Dahie** [comment]
Hi, please give more details to the question. To you mean if java default _Image_ class can convert to dds? Short answer yes, long answer, it depends on the DataBuffer format within the _Image_

**Comment by junglelan** [comment]
for example, how to convert png to DDS?

**Comment by junglelan** [comment]
i find many project codes, but no java code.

**Comment by Dahie** [comment]
OK, two ways with this project:

1) You can use the subproject Dropps which starts a small UI where you drag'n'drop the PNG into and it converts to DDS on the fly.
2) You use the DDSUtil (library) to build your own converter which would propably work similar to the conversion in Radds:
https://github.com/Dahie/DDS-Utils/blob/master/Dropps/src/de/danielsenff/dropps/tasks/ConvertFilesTask.java

More documentation on the Data formats and conversion in this projects is here: https://github.com/Dahie/DDS-Utils/wiki/Technical-Documentation

All parts of the project haven't been updated in a long time, but they still build through an IDEA on modern Java.

**Comment by junglelan** [comment]
thks, i will try it!  👍
