### ISSUE TITLE
Artifacts available?

### ISSUE THREAD

**Issue by Frotty** [Dahie/DDS-Utils#17]
Hi I'm looking fora java dds lib, is there some way to use this as a maven/gradle dependency?

**Comment by Dahie** [comment]
Hi, not yet. When I build the library using jars was still the thing and I moved the other languages later. Feel free to make a PR to refactor it for support of Gradle/Maven.Regards, DahieAm 21.04.2022 01:51 schrieb Frotty ***@***.***>:
Hi I'm looking fora java dds lib, is there some way to use this as a maven/gradle dependency?

**Comment by Frotty** [comment]
Thanks, I will see what I can do. Hoping that the converter is working 😄
